apiVersion: v2
name: gis-lms-backend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: app-template
    repository: https://bjw-s.github.io/helm-charts
    version: "3.6.1"
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5
    condition: postgres.enabled
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: "3.4.0"
    condition: jaeger.enabled
